data:extend({
  {
    type = "double-setting",
    name = "logicarts-fuel-threshold",
    order = "a",
    setting_type = "runtime-global",
    default_value = 0.25,
    minimum_value = 0.1,
    maximum_value = 1.0,
  },
  {
    type = "bool-setting",
    name = "logicarts-grass-wearing",
    order = "a",
    setting_type = "runtime-global",
    default_value = true,
  },
  {
    type = "int-setting",
    name = "logicarts-cart-speed",
    order = "a",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 200,
  },
  {
    type = "int-setting",
    name = "logicarts-cart-consumption-burner",
    order = "a",
    setting_type = "runtime-global",
    default_value = 180,
    minimum_value = 0,
    maximum_value = 300,
  },
  {
    type = "int-setting",
    name = "logicarts-cart-consumption-electric",
    order = "a",
    setting_type = "runtime-global",
    default_value = 18,
    minimum_value = 0,
    maximum_value = 300,
  },
})